### ISSUE TITLE
Document how to make a release; make a release

### ISSUE THREAD

**Issue by Boshen** [oxc-project/oxlint-action#3]

**Comment by Boshen** [comment]
Why do I get a broken page (status 500) when I hit release?

It redirects to https://github.com/oxc-project/oxlint-action/releases with a 

Looks like something went wrong!

We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

**Comment by DonIsaac** [comment]
My guess is it has to do with me publishing an action with the same name under a different repo then removing it from the marketplace. Maybe a bug in GitHub?

**Comment by Boshen** [comment]
Finally figured it out by replacing the name "Oxlint" https://github.com/oxc-project/oxlint-action/releases/tag/v2.0.0
