### ISSUE TITLE
`oxc-project/oxlint-action@latest` tag looks not actually latest

### ISSUE THREAD

**Issue by cocoich** [oxc-project/oxlint-action#4]
first of all, sorry for machine-translated english 🤖 

---

when using oxlint-actions on my `ci.yml`(actions), it links `@latest` tag but fetched version is 2 month ago.
shoud i use `v0` tag? or `v1`?

```yml
- uses: oxc-project/oxlint-action@latest
```

maybe you can reference from `actions/checkout@v4`, i think they update `v4` tags each release.
https://github.com/actions/checkout/actions/workflows/update-main-version.yml

**Comment by Boshen** [comment]
https://github.com/oxc-project/oxlint-action/releases/tag/v2.0.0
